version: "3"

services:
  web:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env

  mongodb:
    image: mongo:6.0.9
    ports:
      - 27017:27017
    volumes:
      - .data/mongodb:/data/db

volumes:
  data:
